# WXY-OECT NAS 专用 Samba 配置
[share]
    comment = WXY-OECT NAS 共享空间
    path = /mnt/data
    browseable = yes
    writable = yes
    guest ok = yes
    create mask = 0644
    directory mask = 0755
    force user = root
    force group = root
    public = yes
    available = yes

[album]
    comment = 手机相册自动备份
    path = /mnt/data/album
    browseable = yes
    writable = yes
    guest ok = yes
    create mask = 0644
    directory mask = 0755
    force user = root
    force group = root
    public = yes
    available = yes